name: upload

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --exclude '.git*/*' --exclude '.gitignore' --exclude '.github/*' --exclude '.github' --exclude 'README.md'
      env:
        AWS_S3_BUCKET: ${{secrets.S3}}
        AWS_ACCESS_KEY_ID: ${{secrets.S3AK}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.S3SK}}
